### ISSUE TITLE
Apache APISIX Container gets restarting when using Docker Compose

### ISSUE THREAD

**Issue by haoren22** [apache/apisix-docker#262] opened 2021-12-27 08:56 UTC
基于docker compose 安装apisix 存在镜像重启问题
[root@localhost /]# mkdir apisix
[root@localhost /]# cd apisix/
[root@localhost apisix]# git clone https://github.com/apache/apisix-docker.git
[root@localhost apisix]# cd apisix-docker/example/
[root@localhost example]# docker-compose -p docker-apisix up -d
上面是执行的命令
结果，就是存在重启问题
CONTAINER ID        IMAGE                                   COMMAND                  CREATED              STATUS                          PORTS                              NAMES
8ce03e3dede8        apache/apisix:2.11.0-alpine             "sh -c '/usr/bin/a..."   About a minute ago   Restarting (1) 39 seconds ago                                      dockerapisix_apisix_1
2f9038d87f78        nginx:1.19.0-alpine                     "/docker-entrypoin..."   About a minute ago   Restarting (1) 41 seconds ago                                      dockerapisix_web1_1

将镜像删除之后
我试着将example的权限改为777，情况还是一样的
[root@localhost apisix-docker]# chmod -R 777 example

这个是具体的容器报错信息
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
failed to read local yaml config of apisix: failed to open file: /usr/local/apisix/conf/config.yaml, error info:/usr/local/apisix/conf/config.yaml: Permission denied
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init

**Comment by juzhiyuan** [comment] 2021-12-27 08:59
Hi @gxthrj, please have a check, thanks!

**Comment by zaunist** [comment] 2021-12-27 10:02
Hi, @haoren22 . I can't reproduce your problem, please try another system deployment.
![image](https://user-images.githubusercontent.com/38528079/147460708-c685288f-c028-4840-91c5-9cb0e76d5e9e.png)

There is my environment:
```
docker: Docker version 20.10.11, build dea9396
docker-compose: docker-compose version 1.29.2, build 5becea4c
os: macOS BigSur
```

**Comment by haoren22** [comment] 2021-12-27 10:39
> Hi, @haoren22 . I can't reproduce your problem, please try another system deployment. ![image](https://user-images.githubusercontent.com/38528079/147460708-c685288f-c028-4840-91c5-9cb0e76d5e9e.png)
> 
> There is my environment:
> 
> ```
> docker: Docker version 20.10.11, build dea9396
> docker-compose: docker-compose version 1.29.2, build 5becea4c
> os: macOS BigSur
> ```



> 嗨，@haoren22。我无法重现您的问题，请尝试其他系统部署。 ![图片](https://user-images.githubusercontent.com/38528079/147460708-c685288f-c028-4840-91c5-9cb0e76d5e9e.png)
> 
> 有我的环境：
> 
> ```
> docker: Docker version 20.10.11, build dea9396
> docker-compose: docker-compose version 1.29.2, build 5becea4c
> os: macOS BigSur
> ```

thank, find by update my env

**Comment by juzhiyuan** [comment] 2021-12-28 01:04
Hi @haoren22, may I know if your issue has been fixed? 😄 If yes, hope you could provide how to debug that issue & fix that issue.

**Comment by haoren22** [comment] 2021-12-28 01:52
> Hi @haoren22, may I know if your issue has been fixed? 😄 If yes, hope you could provide how to debug that issue & fix that issue.

update docker and docker-compose to the latest.

**Comment by juzhiyuan** [comment] 2021-12-28 02:18
OK, could we close this issue?

**Comment by haoren22** [comment] 2021-12-28 08:27
> OK, could we close this issue?

可以了

**Closed** 2021-12-28 10:18 UTC
