### ISSUE TITLE
k8s 环境apisix集成prometheus，apisix和prometheus的配置如何设置？

### ISSUE THREAD

**Issue by wjmmjr** [apache/apisix-docker#203] opened 2021-08-03 03:25 UTC
按照虚拟机的配置方式，apisix和prometheus集成失败

**Comment by Yiyiyimu** [comment] 2021-08-03 17:55
Hi @wjmmjr could you provide some detail steps about how you deploy apisix and prometheus

**Comment by spacewander** [comment] 2021-08-04 00:52
Duplicate of https://github.com/apache/apisix/issues/4744?

**Closed** 2021-08-06 04:13 UTC
