### ISSUE TITLE
[emerg] 1#1: bind() to 0.0.0.0:465 failed (13: Permission denied)

### ISSUE THREAD

**Issue by l36t** [apache/apisix-docker#473] opened 2023-06-06 03:56 UTC
I want to listen tcp service,port is 465,when I start docker,the error is:
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/apisix/conf/nginx.conf:3
2023/06/06 03:52:55 [emerg] 1#1: bind() to 0.0.0.0:465 failed (13: Permission denied)

How can I resolve this problem,thanks

**Comment by hamidrezakhosroabadi** [comment] 2023-06-09 09:32
Can you send steps to reproduce(including configs or commands)?
It's good to see which image are you using and how is your configuration.

the easiest solution is set your desired port on docker port mapping or k8s service.

**Comment by Revolyssup** [comment] 2023-08-01 04:28
@l36t Any updates here? If you're binding a port with port number as low as 465, you will need super user privileges while starting your containers.

**Comment by Sn0rt** [comment] 2023-12-08 06:31
can't reproduce this . close @monkeyDluffy6017

**Comment by monkeyDluffy6017** [comment] 2023-12-08 06:31
I'll close this issue, feel free to reopen it

**Closed by monkeyDluffy6017** 2023-12-08 06:31 UTC
Labels: bug
